[workspace]
members = [
    "contracts/liquidation-filterer",
    "packages/chains/*",
    "packages/outpost",
    "packages/testing"
]

[workspace.package]
version       = "0.1.0"
authors       = [
    "Piotr Babel <piotr@delphilabs.io>",
    "Larry Engineer <larry@delphidigital.io>"
]
edition       = "2021"
repository    = "https://github.com/mars-protocol/liquidation-helpers"
homepage      = "https://marsprotocol.io"
documentation = "https://docs.marsprotocol.io/"
keywords      = ["mars", "cosmos", "cosmwasm"]

[workspace.dependencies]
cosmwasm-schema = "1.1"
cosmwasm-std    = "1.1"
cw2             = "0.16"
cw-storage-plus = "0.16"
cw-utils        = "0.16"
mars-osmosis    = { version = "0.1.0", path = "./packages/chains/osmosis" }
mars-outpost    = { version = "0.1.0", path = "./packages/outpost" }
mars-testing    = { version = "0.1.0", path = "./packages/testing" }
osmosis-std     = "0.13.2"
schemars        = "0.8"
serde           = { version = "1.0", default-features = false, features = ["derive"] }
thiserror       = "1.0"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
